apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: simple-service
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: {{ .Values.ingress.name }}
  namespace: default
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            serviceName: {{ .Values.service.name }}
            servicePort: {{ .Values.service.port }}
